version: '3.9'
services:
  api:
    build: .
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}

  db:
    image: postgres:15
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
