name: Deploy NestJS to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (for context only)
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Install Node.js, pnpm, and PM2
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs npm git
            sudo npm install -g pnpm pm2

            # Clone or update the repo
            if [ ! -d "Service-test" ]; then
              git clone https://github.com/ChathuraJanithya/Service-test.git
            else
              cd Service-test
              git pull origin main
              cd ..
            fi

            # Navigate into the repo
            cd Service-test

            # Install dependencies and build
            pnpm install
            pnpm run build

            # Start or restart the app using PM2
            pm2 start dist/main.js --name service-test || pm2 restart service-test
            pm2 save
